### ISSUE TITLE
Source init.fish or share.fish file by default to allow user to share functions across tests

### ISSUE THREAD

**Issue by bucaran** [fisherman/fishtape#10]
ATM you can create a `_.fish` file which will be sourced before all other tests run, but this is a hack.

It would be great if Fishtape could have a sensible convention to source a file if such file exists.

Somethiing like `init.fish` maybe.

**Comment by bucaran** [comment]
Instead, create a file and name it `_setup.fish` or `_init.fish` and it will be run first by default. This seems simpler and cleaner to me.

**Comment by edouard-lopez** [comment]
As discussed in #30, the filename can be whatever you want as long as it's the first one alphabetically.

### Common scenario
1. `_init.fish`
1. `whatever.fish`

`_init.fish` run first.

### Corner case

Filenames with double underscore come first

1. `__my_test_case.fish`
1. `_init.fish`
1. `whatever.fish`

:warning: `__my_test_case.fish` run first!
