### ISSUE TITLE
Support `-a`

### ISSUE THREAD

**Issue by tuvistavie** [fisherman/fishtape#5]
Writing a test case for each condition can be [a bit verbose](https://github.com/tuvistavie/fundle/blob/master/test/utils_test.fish#L37) so it would be nice if `-a` was supported.
I am not sure if it is already supposed to be supported, but for example

```
test "$TESTNAME: DIRNAME is the directory name FILENAME"
  \( $DIRNAME = (dirname $FILENAME) \) -a \( $DIRNAME != (dirname $FILENAME) \)
end
```

does not fail.

**Comment by bucaran** [comment]
@tuvistavie Not impossible, but difficult to implement, simply because the `test` builtin is being **overloaded** in favor of IMO a more useful test, to check whether a list contains one or more items.

So, instead of

```fish
test
    lt = "lt" = (__fundle_compare_versions 0.1.0 0.1.1) -a "gt" = (__fundle_compare_versions 0.1.2 0.1.1)
end
```

consider

```fish
test (
    __fundle_compare_versions 0.1.0 0.1.1
    __fundle_compare_versions 0.1.2 0.1.1
    __fundle_compare_versions 0.1.2 0.1.2
    __fundle_compare_versions 0.10.0 0.2.2
    __fundle_compare_versions 0.10.0 1.2.2) = (printf "%s\n" lt gt eq gt lt)
end
```

Does that work out for you?

**Comment by tuvistavie** [comment]
@bucaran Thanks, that works for my current use case and the other I had in mind. `-a` is probably a little more readable, but I don't think it is worth the eventual complexity so I'll close this for now.
I'll reopen if I find a case where `-a` could be really beneficial.

**Comment by bucaran** [comment]
@tuvistavie I agree and this is still subject to change. The Fisherman test suite is pretty large too and I bumped into this issue a couple of times already, but always preferred the overloaded `contains`.

Let's give it some time. Like I said, the implementation is not impossible, but may require dropping the overloaded contains and perhaps add a special operator `~` and `!~` for it instead.
